name = input("Enter a name: ")
adj = input("Enter an adjective: ")
adj2 = input("Enter an adjective: ")
ad = input("Enter an adverb: ")
foo = input("Enter a food: ")
foo2 = input("Enter another food: ")
noun = input("Enter a noun: ")
place = input("Enter a place: ")
verb = input("Enter a verb: ")


print("\n")
print(name + " was planning a dream vacation to " + place + ".")
print(name + " was especially looking forward to trying the local ")
print( "cuisine, including " + adj + foo + " and " + foo2 + ".")
print("\n")
print(name + " will have to practice the language " + ad + " to ")
print( "make it easier to " + verb + " with people.")
print("\n")
print(name + " has a long list of sights to see, including the ")
print(noun + " museum and the " + adj2 + " park. ")