name = input("Enter a name: ")
game = input("Enter a game: ")
foo = input("Enter a food: ")
foo2 = input("Enter another food: ")
noun = input("Enter a noun: ")
adj = input("Enter an adjective: ")
adj2 = input("Enter an adjective: ")
verb = input("Enter a verb: ")
ad = input("Enter an adverb: ")


print("\n")
print(f"{name} loves to sit and play {game}. {name} also likes to eat {foo} and {foo2}. " )
print(f"{noun} is the place I like to go  I like {adj} {adj2} hair ALOT. ")
print("\n")
print(f"{verb} I went to the store and looked {ad}.")
print("The End")
